### ISSUE TITLE
build error with appconfig

### ISSUE THREAD

**Issue by dxjia** [edinbb/fitbit-air-quality-app#1]
Hi, I'm trying to build this app on my own, but it's failing on missing ./appconfig for companion.
Could you please share how can I setup one? thanks very much.

**Comment by edinbb** [comment]
Hi, add appconfig.js to the companion folder. The format of the file:
 
`export const CONFIG = {
  app: {
    name: 'AirQuality',
    version: '4.2.0',
  },
  trackingId: <google analytics id>,
  enableTracking: true,
  token: <token from https://aqicn.org/api/>,
  wakeInterval: {
    values: [
      {
        name: 'Hourly',
        value: 3600000,
      },
    ],
    selected: [
      0,
    ],
  },
};`

Hope this helps. Regards

**Comment by dxjia** [comment]
@edinbb 
Hi,
thanks very much, this resolves the build error completely.
I'm going to close this issue.

Best Wishes.
